apiVersion: 1

datasources:
- name: Prometheus
  type: prometheus
  url: http://prometheus:9090
  access: proxy
  isDefault: true
  editable: false
- name: Loki
  type: Loki
  url: http://loki:3100
  access: proxy
  orgId: 1
  basicAuth: false
  isDefault: true
  version: 1
  editable: true